### ISSUE TITLE
Milestone 1 Task Trackers

### ISSUE THREAD

**Issue by huijuechen** [UBC-MDS/Hours_Spent_On_Labs_Survey#1]
- [x] Decide and agree upon a collaboration strategy

- [x] Add a code of conduct for contributing

--- **In the proposal:**-----
- [x] Identify the question that your team in interested in answering with the survey.

- [x] Identify the other questions you plan to ask in your survey to identify confounding variables and justify/explain why you plan to include them.

- [x] Describe how you plan to analyze the survey results

- [x] Discuss the aspects of the [UBC Office of Research Ethics document](https://ethics.research.ubc.ca/sites/ore.ubc.ca/files/documents/Online_Survey-GN.pdf) on Using Online Surveys that are relevant to your proposed survey.
