### ISSUE TITLE
Milestone 3 Task Tracker

### ISSUE THREAD

**Issue by bettybhzhou** [UBC-MDS/Hours_Spent_On_Labs_Survey#23]
Your target audience is other Data Scientists who are not familiar with your project.
- [x] Clearly introduce the survey topic and question you were interested in answering.
- [x] Link to your study's data and code in the methods section of your report.
- [x] Include effective visualizations and/or tables that help communicate your findings.

Your discussion should have 2 key focuses:
- [x] Discussing the results and findings of your survey and analysis of the survey data.
Discussing your survey/study design, specifically:
- [x] what did you do well to make this study as causal as possible?
- [x] what was not done well and how did that affect your studies conclusions?
- [x] what would you do differently next time to improve your survey/study design and why?
